[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
safejar = "ADLcQek3XxLbxdj8wrzZ5gjAoYntLACHZtvchrmtqJaq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tmp/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
